from tkinter import *

def click(event):
   text = event.widget.cget("text")
   print(text)
   if text == "=":
        if scvalue.get().isdigit():
            value = int(scvalue.get())
        else:
            value = eval(screen.get())
        scvalue.set(value)
        screen.update()
   elif text == "c":
       scvalue.set("")
       screen.update()
   else:
       scvalue.set(scvalue.get() + text)
       screen.update()

root = Tk()
root.geometry("394x285")
root.minsize(125,165)
root.maxsize(1100,845) 
root.title("fist project")
f1 = Frame(root, bg="black", borderwidth=6)
f1.pack(side=LEFT, fill="y")
anshul = Label(f1, text="(she)  is my dog\n  gorgeous", bg="sea green")
anshul.pack( pady=100)
scvalue = StringVar()
scvalue.set("")
screen = Entry(root, textvar=scvalue, font=" lucida 20 bold"  )
screen.pack(fill="x", ipadx=15, pady=20, padx=20)
f= Frame(root, bg="blue")
b= Button(f, text="c")
b.pack(side=LEFT, padx=15, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="-")
b.pack(side=LEFT, padx=15, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="+")
b.pack(side=LEFT, padx=15, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="/")
b.pack(side=LEFT, padx=15, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text=".", font=" lucida 10 bold")
b.pack(side=LEFT, padx=14, pady=8)
b.bind("<Button-1>", click)

f.pack()
f= Frame(root, bg="blue")
b= Button(f, text=" 0")
b.pack(side=LEFT, padx=16, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="9")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="8")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="7")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="6")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)

f.pack()
f= Frame(root, bg="gray")
b= Button(f, text="5")
b.pack(side=LEFT, padx=16, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="4")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="3")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="2")
b.pack(side=LEFT, padx=14, pady=10)
b.bind("<Button-1>", click)
b= Button(f, text="1")
b.pack(side=LEFT, padx=16, pady=10)
b.bind("<Button-1>", click)

f.pack()
f= Frame(root, bg="red", padx=40, pady=5)
b= Button(f, text="=", font=" lucida 15 bold")
b.pack(side=LEFT, padx=16, pady=5)
b.bind("<Button-1>", click)
f.pack()



root.mainloop()